kripken/ammo.js

ammo.idl

Added `setMargin` method to some shape classes that I've tested. They are `btBoxShape`, `btCapsuleShape`, `btCapsuleShapeX`, `btCapsuleShapeZ`, `btCylinderShape`, `btCylinderShapeX`, `btCylinderShapeZ`, `btSphereShape`, `btCompoundShape`.
The `setMargin` method is needed when creating small pieces for example.
`btConeShape` has no `setMargin()` in Bullet.
Another shape I want to add in the future is `btConvexHullShape`
And also added `setMotionState` method to `btRigidBody`, needed in my editor and also I think people using kinematic objects will need it.

Added setMargin method to some shape classes, and setMotionState to btRigidBody

---

ammo.idl
tests/userData.js

Another little addition to the IDL. These 4 functions are used to get and set the user index or pointer (wathever the user finds more useful) to each bullet object.
The user values are used to store references to visual objects for example. In my case I use them to store objects ids and retrieve them when iterating through contact points, where I have access to the rigid bodies in contact. This way I know which collision event handler to call.
I've made a test under "tests/userData.js" and tested it in the web browser.

Added user pointer and index getters/setters to IDL

---

README.markdown

It previously pointed to a nonexistent wiki page. Now it points to the getting started page on the project's website.

Fix broken link to getting started page

---

README.markdown
bullet/src/BulletCollision/CollisionDispatch/btCollisionWorld.cpp
bullet/src/BulletCollision/NarrowPhaseCollision/btRaycastCallback.h

Integrated RayCast fix from https://github.com/bulletphysics/bullet3/commit/7151865c16ba996996206e1fd7869cbb1e7edd8d
This solves an issue where starting a raycast from inside a physics object would result it being the first object hit by the raycast which is undesirable.

Patched Bullet to include Raycast fix from 2.83 

---

ammo.idl

This PR adds:
btVector3:
+  [Value] btVector3 rotate([Ref] btVector3 wAxis, float angle);
btQuaternion:
+  [Value] btQuaternion inverse();
+  float getAngle();
+  float getAngleShortestPath();
+  float angle([Ref] btQuaternion q);
+  float angleShortestPath([Ref] btQuaternion q);
+  float length2();
+  float length();
+  float dot();
+  [Operator="+=", Ref] btQuaternion op_add([Ref] btQuaternion q);
+  [Operator="-=", Ref] btQuaternion op_sub([Ref] btQuaternion q);
+  [Operator="*=", Ref] btQuaternion op_mul(float s);
+  [Operator="*=", Ref] btQuaternion op_mulq([Ref] btQuaternion q);
+  [Operator="/=", Ref] btQuaternion op_div(float s);
+  void setRotation([Ref] btVector3 axis, float angle);
I followed the method listed [https://github.com/kripken/ammo.js/issues/60](here), hope it's OK. …

Add a bunch of btQuaternion methods 

---

ammo.idl

I needed these two methods for a project, so I added them.
```
boolean isStaticObject();
boolean isStaticOrKinematicObject();
```
OT: The Python scripts should either be ported to support Python3 as well (which is probably trivial - just add parentheses to all `print`s) or explicitly require Python2 (e.g. by changing the shebang to `#!/usr/bin/env python2` or with an error message if Python3 is being used).
Since Python3 is now the default on many platforms, I'd recommend the first solution.

add 2 methods to btCollisionObject

---

examples/webgl_demo/ammo.html
examples/webgl_demo/ammo.wasm.html
examples/webgl_demo/worker.js
examples/webgl_demo_softbody_cloth/index.html
examples/webgl_demo_softbody_rope/index.html
examples/webgl_demo_softbody_volume/index.html
examples/webgl_demo_softbody_volume2/index.html
examples/webgl_demo_terrain/index.html
examples/webgl_demo_vehicle/index.html

Couldn't fix the wasm demo though.
#170

Fixed examples.

---

ammo.idl

**In btCollisionShape:**
[Const, Ref] btVector3 getLocalScaling(); 
**In btRigidBody:**
void applyGravity(); 
[Const, Ref] btVector3 getGravity(); 
void setGravity([Const, Ref] btVector3 acceleration); 
**In btCollisionWorld:**
void updateSingleAabb([Const] btCollisionObject colObj);
Added functions tested in with an [Armory](http://armory3d.org/) HTML5/JS build, and working fine!
All ammo.js test cases passed, no issues (ran them manually using ```node ../builds/ammo.js ./basics.js``` etc).

Added couple of functions to ammo.idl

---

make.py

Broke worker processes on windows. See kripken/emscripten#6017.
This is a really ugly diff, but I only made three minor changes: wrap the script body in `def build():` and indent, move the `stage_counter` variable back to the top to keep it `global`, and add an `if __name__ == '__main__':` check before executing everything.

Fix: make.py not importable

---

README.markdown
make.py

need Pointer_stringify to print out DOMStrings from `btIDebugDraw` `reportErrorWarning` and `draw3dText`.

add Pointer_stringify to EXPORTED_RUNTIME_METHODS

---

ammo.idl

Also add getBroadphaseProxy() to btRigidBody. This appears to be the best way to modify collisionFilterGroup and collisionFilterMask on an body without removing/re-adding it to the world.

add btBroadphaseProxy to ammo.idl

---

ammo.idl
idl_templates.h
make.py

This gives you easy access to the vertices/faces/normals that btConvexHull computes for you, so you can properly render convex hulls.

 add btConvexPolyhedron to ammo.idl

---

ammo.idl

To efficiently generate a `btBvhTriangleMeshShape` with scaling, you need to construct a `btTriangleMesh` and call [this `setScaling` method](https://pybullet.org/Bullet/BulletFull/classbtStridingMeshInterface.html#a7963a24451e7c5c19f37da558993683a) on it prior to constructing the `btBvhTriangleMeshShape` -- if you instead call `setLocalScale` on the `btBvhTriangleMeshShape` after construction, it will have to rebuild the whole BVH.

Expose btStridingMeshInterface.setScaling in IDL

---

ammo.idl

Im surprised no one else is getting these missing ammo.idl entries.
No one **MUST NOT** have been using things like (not without all the recent ammo.idl changes): 
- Kinematic Character Controllers
- Ghost Object Collision Detection
- Global Contact Processing Callbacks
- Detail Rigidbody Configuration (Linear/Angular Factors And Damping)
And other advanced physics using Ammo.js out-the-box... But these ammo.idl changes ought to help with the next guy who comes along and want to get to the **Nitty Gritty** of using the buttlet API in JavaSciript eco-system using Ammo.js :)

getNumOverlappingPairCache

---

ammo.idl

I needed the existing `btEmptyShape` so added it to the IDL. Perhaps someone will need it also one day.
Also moved the btConeShapeX and Z just below the btConeShape, just to keep things organized.

Add btEmptyShape to IDL

---

make.py
test.py

In make.py import tools/building.py instead of tools/shared.py from emscripten.
In test.py look for .emscripten using the EMSDK environment variable before looking in user's home.

Small emscripten-tool-related changes to make.py and test.py

---

.gitignore
CMakeLists.txt
Makefile
ammo.h
bullet/CMakeLists.txt
idl_templates.h
make.py

Adds support for cmake builds. This simplifies interaction with bullet quite a bit, you can build javascript and wasm flavors of ammo with closure post processing like this:
```bash
$ cd builds
$ cmake .. -DCLOSURE=1
$ make
```
`-DTOTAL_MEMORY`, `-DALLOW_MEMORY_GROWTH`, `-DADD_FUNCTION_SUPPORT` can be passed to cmake as well.

feat: CMake Build

---

bullet/src/LinearMath/btVector3.h

Patches bullet btVector3 BT_SHUFFLE for clang >= 8
Cherry-picked from  https://github.com/bulletphysics/bullet3/pull/2232/files

fix: Can't build native bullet with clang >= 8

---

ammo.idl

The change adds the collision object to the convex shape sweep test result.

Add collision object to convex shape cast result

---

.github/workflows/continuous.yml

Fixes build errors from deprecated `add-path` and `set-env` surfacing in #352
More info at https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

Fix CI workflow deprecation errors

---

README.markdown
docker-compose.yml

The Docker build system introduced in #265 is currently broken (it relies on `build.sh` which has been dropped) and not documented while very useful in my point of view (among others, to build `ammojs` from macOS).
This PR fixes this:

Fix docker build

---

ammo.idl

When a raytest is performed, it may return the backface hit result:
```
var rayCallback = new Ammo.AllHitsRayResultCallback(start, end);
dynamicsWorld.rayTest(start, end, rayCallback);
```
Exposing the flag on the callback allows us to set it so that the backfaces are ignored:
```
var rayCallback = new Ammo.AllHitsRayResultCallback(start, end);
rayCallback.set_m_flags(1 << 0);
dynamicsWorld.rayTest(start, end, rayCallback);
```

Expose m_flags in RayResultCallback

---

examples/webgl_demo/ammo.html
examples/webgl_demo/ammo.wasm.html
examples/webgl_demo/worker.js
examples/webgl_demo/worker.wasm.js

Can not restart the simulation after we first load that page.
the **poseMessage** in ammo.html or ammo.wasm.html may be called before ammo.js is initialized in web workers. So, I made a little change to fix this error.

fixed a bug in examples/webgl_demo

---

ammo.idl

The btMotionState is meant to be used in a callback like fashion for performance reasons and I found that there was really no way to use it that way without this additional binding.
How to use:
```js
const motionState = new Ammo.MotionState();
motionState.getWorldTransform = (transformRef) => {
const btTransform = Ammo.wrapPointer(transformRef, Ammo.btTransform);
// update the transform from your render state
// i.e. btTransform.setOrigin(), btTransform.setRotation()
}
motionState.setWorldTransform = (transformRef) => {
const btTransform = Ammo.wrapPointer(transformRef, Ammo.btTransform);
// update your render state from the transform
// i.e. btTransform.getOrigin(), btTransform.getRotation()
}
const rigidBodyInfo = new Ammo.btRigidBodyConstructionInfo(mass, motionState, ammoShape, …
```

added support for JSImplementation of btMotionState
